---
resources:
- name: cf-rabbitmq-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/cf-rabbitmq-release.git
    branch: master
    private_key: {{git-ssh-key}}

jobs:
- name: test
  plan:
  - get: cf-rabbitmq-release
    trigger: true
  - task: test
    file: cf-rabbitmq-release/src/rabbitmq-broker/ci/run-tests.yml
